# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: poetry\.lock
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
