name: Send notifications

on:
  workflow_dispatch:
  schedule:
    - cron: '50 5 * * *'  # At 05:50 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.9.4

      - name: Execute py script
        env:
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
        run: uv run --locked --no-dev src/main.py
