name: Send notifications

on:
  workflow_dispatch:
  schedule:
    - cron: '50 5 * * *'  # At 05:50 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --no-dev

      - name: Execute py script
        env:
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
        run: uv run python src/main.py
